Simulationhospitalreception/config/routes.rb
Rails.application.routes.draw do
  resources :children_receivings
  

  root 'children_receivings#index'

end

Simulationhospitalreception/app/models/children_receiving.rb
class ChildrenReceiving < ActiveRecord::Base
end

Simulationhospitalreception/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Simulationhospitalreception/app/controllers/children_receivings_controller.rb
class ChildrenReceivingsController < ApplicationController
  before_action :set_children_receiving, only: [:show, :edit, :update, :destroy]

  # GET /children_receivings
  # GET /children_receivings.json
  def index
    @children_receivings = ChildrenReceiving.all
  end

  # GET /children_receivings/1
  # GET /children_receivings/1.json
  def show
  end

  # GET /children_receivings/new
  def new
    @children_receiving = ChildrenReceiving.new
  end

  # GET /children_receivings/1/edit
  def edit
  end

  # POST /children_receivings
  # POST /children_receivings.json
  def create
    @children_receiving = ChildrenReceiving.new(children_receiving_params)

    respond_to do |format|
      if @children_receiving.save
        format.html { redirect_to @children_receiving, notice: 'Children receiving was successfully created.' }
        format.json { render :show, status: :created, location: @children_receiving }
      else
        format.html { render :new }
        format.json { render json: @children_receiving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children_receivings/1
  # PATCH/PUT /children_receivings/1.json
  def update
    respond_to do |format|
      if @children_receiving.update(children_receiving_params)
        format.html { redirect_to @children_receiving, notice: 'Children receiving was successfully updated.' }
        format.json { render :show, status: :ok, location: @children_receiving }
      else
        format.html { render :edit }
        format.json { render json: @children_receiving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children_receivings/1
  # DELETE /children_receivings/1.json
  def destroy
    @children_receiving.destroy
    respond_to do |format|
      format.html { redirect_to children_receivings_url, notice: 'Children receiving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_children_receiving
      @children_receiving = ChildrenReceiving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def children_receiving_params
      params.fetch(:children_receiving, {})
    end
end

Simulationhospitalreception/app/helpers/application_helper.rb
module ApplicationHelper
end

Simulationhospitalreception/app/helpers/children_receivings_helper.rb
module ChildrenReceivingsHelper
end

Simulationhospitalreception/app/views/children_receivings/_form.html.erb
<%= form_for(@children_receiving) do |f| %>
  <% if @children_receiving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@children_receiving.errors.count, "error") %> prohibited this children_receiving from being saved:</h2>

      <ul>
      <% @children_receiving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Simulationhospitalreception/app/views/children_receivings/edit.html.erb
<h1>Editing Children Receiving</h1>

<%= render 'form' %>

<%= link_to 'Show', @children_receiving %> |
<%= link_to 'Back', children_receivings_path %>

Simulationhospitalreception/app/views/children_receivings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recepcion de ninos en un hospital</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>


<%= form_tag({controller: :children_receivings, action: :index}, method: :put) do %>

<div class="form-group">
            <%= label_tag :name, 'Primer nombre' %>
            <%= text_field_tag :name,"", placeholder: 'digite su primer nombre', class: "form-control" %>
          </div>


<div class="form-group">
            <%= label_tag :name, 'Segundo nombre' %>
            <%= text_field_tag :name, "", placeholder: 'digite su segundo nombre', class: "form-control" %>
          </div>

          <div class="form-group">
            <%= label_tag :lastname, 'Primer apellido' %>
            <%= text_field_tag :lastname, "", placeholder: 'digite su primer apellido', class: "form-control" %>
          </div>

<div class="form-group">
            <%= label_tag :name, 'Segundo apellido' %>
            <%= text_field_tag :name, "", placeholder: 'digite su segundo apellido', class: "form-control" %>
          </div>

  <div class="form-group">
          <%= label_tag :birthday, 'Fecha de nacimiento' %>
          <%= date_select :birthday, "birthday",start_year: 1920, end_year: 2016,class: "form-control" %>
  </div>

<div class="form-group">
            <%= label_tag :email, 'E-mail' %>
            <%= text_field_tag :email, "", placeholder: 'digite correo electronico de contacto', size: "40x40", class: "form-control" %>
          </div>

  <div class="form-group">
    <%= label_tag :sex_sel, 'Genero' %>
    <%= select_tag :sex_sel, options_for_select(["Masculino", "Femenino"]), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :message, "Enfermedades que padece o ha padecido:" %>
    <p><%= text_area_tag(:message,"", size: "24x6", class: 'form-control') %></p>
  </div>


  <div>
    <%= label_tag(:newsletter, "Alguna vez ha padecido desnutricion?") %>
    <%= label_tag :newsletter_accept_yes, "Si" %>
    <%= radio_button_tag(:newsletter_accept, "yes") %>

    <%= label_tag :newsletter_accept_no, "No" %>
    <%= radio_button_tag(:newsletter_accept, "no") %>
  </div>



  <%= form_tag("/accept-terms", method: "post", class: "nifty_form") do %>
   <div>
    <%= label_tag(:terms_conditions, "Desea aceptar los terminos y condiciones?") %>
    <%= check_box_tag(:terms_conditions) %>
    </div>
  
  <div>
    <%= label_tag(:newsletter, "Desea recibir notificaciones semanales?") %>
    <%= label_tag :newsletter_accept_yes, "Si" %>
    <%= radio_button_tag(:newsletter_accept, "yes") %>

    <%= label_tag :newsletter_accept_no, "No" %>
    <%= radio_button_tag(:newsletter_accept, "no") %>
  </div>
  

  <div class="form-group">
  <%= submit_tag "Enviar formulario", class: "btn btn-success" %>
  <button class="btn btn-danger">Cancelar</button>
  </div>

<% end %>


<% end %>
        



  <tbody>
    <% @children_receivings.each do |children_receiving| %>
      <tr>
        <td><%= link_to 'Show', children_receiving %></td>
        <td><%= link_to 'Edit', edit_children_receiving_path(children_receiving) %></td>
        <td><%= link_to 'Destroy', children_receiving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo nino para tratamiento', new_children_receiving_path %>

Simulationhospitalreception/app/views/children_receivings/new.html.erb
<h1>New Children Receiving</h1>

<%= render 'form' %>

<%= link_to 'Back', children_receivings_path %>

Simulationhospitalreception/app/views/children_receivings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_children_receiving_path(@children_receiving) %> |
<%= link_to 'Back', children_receivings_path %>

Simulationhospitalreception/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simulationhospitalreception</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>